version: 2

sources:
  - name: db
    description: 'DESCRICAO DO BANCO DE DADOS'
    schema: bra_bronze
    tables:
      - name: magento_customer_bonus
      - name: magento_magento_rma_grid
 

      